### ISSUE TITLE
Placeholder?

### ISSUE THREAD

**Issue by juanbrujo** [joseluisq/vue-input-number#1]
How can I add a placeholder to the input?

**Comment by joseluisq** [comment]
> How can I add a placeholder to the input?

It is not supported by default but you can send a PR to adding this prop.

Something like: 

```html
<input type="text" :maxlength="maxlength" autocomplete="off" :placeholder="placeholder" ...
```

```js
export default {
  props: {
    placeholder: {
      type: String,
      default: ''
    }
// ...

**Comment by joseluisq** [comment]
Done [v0.1.2](https://github.com/joseluisq/vue-input-number/releases/tag/v0.1.2)
