### ISSUE TITLE
Default value not :min

### ISSUE THREAD

**Issue by juanbrujo** [joseluisq/vue-input-number#3]
Hehe sorry bothering again, related to the merged PR with :placeholder improvement, emerged another issue: default value is taken from min default data, and in my case it is not showing the placeholder, just if I delete the min value but it re-appears:

![mar-19-2018 11-48-07](https://user-images.githubusercontent.com/362186/37602861-0d18f018-2b6c-11e8-953d-c62369ffb963.gif)

**Comment by joseluisq** [comment]
Because when `keyup` event is fired the value (`quantity` value) is checked.

refs: https://github.com/joseluisq/vue-input-number/blob/master/index.vue#L182

To solve this, I guess that a if statement is needed in asking if placeholder is not empty.

Happy if you can send some PR.

**Comment by juanbrujo** [comment]
but what about the min being used as default value?

**Comment by joseluisq** [comment]
Solved in [v0.1.3](https://github.com/joseluisq/vue-input-number/releases/tag/v0.1.3)

**Comment by juanbrujo** [comment]
great! 👏 I was thinking (not my case) what if someone needs a default value? maybe a `:value` prop could be useful.

**Comment by joseluisq** [comment]
> great! 👏 I was thinking (not my case) what if someone needs a default value? maybe a :value prop could be useful.

Yeah, in that case it could be useful. Maybe you can send a some PR about.
