### ISSUE TITLE
Create new prop 'value'

### ISSUE THREAD

**Issue by baronkoko** [joseluisq/vue-input-number#8]
Hi. Can we create a new prop 'value' to initialize input with that value? Like that - https://codepen.io/Baronkoko/pen/GGEdNd

**Comment by joseluisq** [comment]
Sure, can you send a PR?

**Comment by baronkoko** [comment]
Sure. Can i get access to do that?

**Comment by joseluisq** [comment]
Forking the repository and send me a PR.

**Comment by joseluisq** [comment]
Fixed #9
